# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
