# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160222_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='repos',
            name='owner',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
