# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_repos_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='repos',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
