# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikeway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('bad', 'Bad'), ('regular', 'Regular'), ('good', 'Good')], max_length=255)),
                ('length', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BikewayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_separated', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bikeway',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeways.BikewayCategory'),
        ),
    ]
