# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeway',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
